print("Hacking...")
print("World")
print("Igira")
print("by")
print("igira")
a = input("Введите код:")
print("1 - Хакерский чат")
print("2 - Взлом WIFI")
print("3 - Взлом Выборов")
print("4 - Взлом ЧМ по футболу")
print("5 - Взлом камер")
b = input("Выберите пункт:")
print("Это с@ка шутка :)")